apiVersion: v1
kind: Pod
metadata:
  name: cap-sys-nice-docker
  annotations:
    container.apparmor.security.beta.kubernetes.io/cap-sys-nice-docker: unconfined
spec:
  containers:
  - name: cap-sys-nice-docker
    image: fredrikfornwall/cap-sys-nice-docker:0.1
    securityContext:
      capabilities:
        add: ["SYS_NICE"]
